// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.Recipes
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("count")]
        public long Count { get; set; }

        [JsonProperty("recipes")]
        public Recipe[] Recipes { get; set; }
    }

    public partial class Recipe
    {
        [JsonProperty("instructions")]
        public string Instructions { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("ingredients")]
        public string[] Ingredients { get; set; }
    }
}
